---
title: "Week 10-11: Kernel Density & Troubleshooting" 
subtitle: "SURA 2022"
author: "Shih-Ting (Cindy) Huang"
date: '2022-07-29'
output: html_document
---

```{r setup, message=FALSE, warning=FALSE, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE)

library(tidyverse)
library(dplyr)
library(sf)
library(mapview)
library(RColorBrewer)
library(dbscan)
library(fpc)
library(lwgeom)
library(concaveman)
library(leafpop)
```

```{r load-data, echo=FALSE, include=FALSE}
# Run the script to preprocess fire datasets to include information on time, location, and FRP
# This will limit our observations to those in California
# Object created: "fire", "in_cali" datasets
url1 <- "https://raw.githubusercontent.com/cindyellow/SURA-2022/main/preprocess_fire_txt.R"
if (!file.exists("../preprocess_fire_txt.R"))
  download.file(url1, destfile = "../preprocess_fire_txt.R")
source("../preprocess_fire_txt.R")

# Run the script to preprocess smoke dataset, including additional information on smoke area
# Object created: "smoke" dataset
url2 <- "https://raw.githubusercontent.com/cindyellow/SURA-2022/main/preprocess_smoke_kml.R"
if (!file.exists("../preprocess_smoke_kml.R"))
  download.file(url2, destfile = "../preprocess_smoke_kml.R")
source("../preprocess_smoke_kml.R")
```


## Scraping for 2015

```{r}
library(XML)
url<-c("https://satepsanone.nesdis.noaa.gov/pub/FIRE/web/HMS/Fire_Points/Text/2015/01")
doc<-htmlParse(url)
#get <a> nodes.
Anodes<-getNodeSet(doc,"/a")
#get the ones with .zip's and .gz's
files<-grep("*.txt",sapply(Anodes, function(Anode) xmlGetAttr(Anode,"href")),value=TRUE)
#make the full url
urls<-paste(url,files,sep="")
#Download each file.
mapply(function(x,y) download.file(x,y),urls,files)
```

```{r}
website <- xml2::read_html("https://satepsanone.nesdis.noaa.gov/pub/FIRE/web/HMS/Fire_Points/Text/2015/01")

counts <- xml2::xml_find_first(website, "/html/body/table/tbody/tr[4]/td[2]/a")

str(doc)
```


```{r}
library(polite)
# Device
url <- "https://satepsanone.nesdis.noaa.gov/pub/FIRE/web/HMS/Fire_Points/Text/2015/01"
# Provide informative user_agent details
target <- bow(url,
              user_agent = "cindyy.huang@utoronto.ca for research project",
              force = TRUE)
target
```

## KDE: Fire Points

```{r}
library(spatstat)
library(data.table)
dense.ca.window = "../ca-state-boundary/CA_State_TIGER2016.shp" %>%
  st_read(quiet = TRUE) %>% st_union() %>% 
  st_transform(crs = 3310) %>% st_coordinates() %>% 
  data.table() %>% 
  mutate(x = rev(X / 1e4), y = rev(Y / 1e4)) %>% 
  select(x, y) %>% data.table()

dates <- seq(as.Date("2018-11-07"), as.Date("2018-11-16"), by=1)
fire.dense.dat <- c()

for (d in as.list(dates)){
  fire.ppp = in_cali %>%
    filter(date == d) %>%
    st_coordinates() %>% data.table() %>% 
    mutate(x = X / 1e4, y = Y / 1e4) %>% select(x, y) %>% 
    as.ppp(X = ., W = owin(poly = dense.ca.window))  
  fire.dense = fire.ppp %>% 
    density(kernel = "gaussian",
            sigma = bw.scott(fire.ppp)[2],
            diggle = TRUE,
            dimyx = c(114, 126))
  day.dense.dat = data.table(
    expand.grid(x = fire.dense$xcol * 1e4,
                y = fire.dense$yrow * 1e4),
    fire.dense$v %>% t %>% as.data.table() %>% melt %>%
      select(density = value)) %>% na.omit() %>%
    st_as_sf(coords = c("x", "y"), crs = 3310) %>%
    st_transform(4326) %>%
    cbind(., st_coordinates(.)) %>% st_drop_geometry() %>%
    select(lon = X, lat = Y, density) %>% 
    mutate(date = d) %>%
    data.table()  
  
  fire.dense.dat <- rbind(fire.dense.dat, day.dense.dat)
}

```

```{r}
cal <- "../ca-state-boundary/CA_State_TIGER2016.shp" %>%
  st_read(quiet = TRUE) %>% st_union() %>% st_sf() %>%
  st_transform(4326)

trans.theme = theme(
  rect = element_rect(fill = "transparent"),
  panel.background = element_rect(fill = "transparent"), # bg of the panel
  plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
  panel.grid = element_blank(),
  panel.border = element_blank(),
  axis.ticks = element_blank(),
  axis.text = element_blank(),
  axis.title = element_blank())

fire.dense.dat %>% 
  filter(density >= 2 & date == "2018-11-16") %>%
  mutate(density_cut = cut(density, c(2, seq(10, 80, by = 10)))) %>% 
  ggplot() +
  geom_sf(data = cal, color = "goldenrod", fill = NA) +
  geom_point(aes(x = lon, y = lat, color = density_cut),
             shape = 15, size = 1.5) +
  scale_color_viridis_d() +
  labs(color = "Fire / 100 km2") + 
  trans.theme
```


## KDE: AQS Points

```{r}
# Read AQS data and restrict to campfire week
aqs <- read.delim("../data/AQS_PM25_2000_2021_Cali.csv", sep=",", strip.white=TRUE)
aqs <- aqs %>%
  filter(Date > "2018-11-06" & Date < "2018-11-17")

# Create geometry object for coordinates (used for sf calculations)
aqs <- aqs %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326, remove=FALSE) %>%
  st_transform(3310)

aqs.dense.dat <- c()

for (d in as.list(dates)){
  aqs.ppp = aqs %>%
    filter(Date == d) %>%
    st_coordinates() %>% data.table() %>% 
    mutate(x = X / 1e4, y = Y / 1e4) %>% select(x, y) %>% 
    as.ppp(X = ., W = owin(poly = dense.ca.window))  
  aqs.dense = aqs.ppp %>% 
    density(kernel = "gaussian",
            sigma = bw.scott(aqs.ppp)[2],
            diggle = TRUE,
            dimyx = c(114, 126))
  day.dense.dat = data.table(
    expand.grid(x = aqs.dense$xcol * 1e4,
                y = aqs.dense$yrow * 1e4),
    aqs.dense$v %>% t %>% as.data.table() %>% melt %>%
      select(density = value)) %>% na.omit() %>%
    st_as_sf(coords = c("x", "y"), crs = 3310) %>%
    st_transform(4326) %>%
    cbind(., st_coordinates(.)) %>% st_drop_geometry() %>%
    select(lon = X, lat = Y, density) %>% 
    mutate(date = d) %>%
    data.table()  
  
  aqs.dense.dat <- rbind(aqs.dense.dat, day.dense.dat)
}
```









